const rootDefs = require("./rootDefs.js");

const {
  roomCreatedOrUpdatedSubscription,
  createCommentSubscription,
  createVideoSubscription,
  videoChatRequestSubscription,
  changePlanSubscription,
  buyLikesSubscription,
  buyMessagesSubscription,
  buyMinutesSubscription,
  flagUserSubscription,
  userMatchedSubscription,
} = require("./subscription/subscription");

const {
  fetchMeResolver,
  getRoomsResolver,
  getCommentsResolver,
  findUserResolver,
  getUsersMapResolver,
  getAllUsersResolver,
  getVideosResolver,
  getLikedUsersResolver,
  getUsersWhoLikedMeResolver,
  getMatchedUsersResolver,
  getFlaggedPicturesResolver,
  getFlaggedVideosResolver,
  getRealUsersResolver,
} = require("./queries");
const {
  createRoomResolver,
  changeRoomResolver,
  googleSignupResolver,
  googleLoginResolver,
  signupResolver,
  loginResolver,
  logoutResolver,
  createCommentResolver,
  createProfileResolver,
  updateLocationResolver,
  addPhotoResolver,
  sendVideoResolver,
  deletePhotoResolver,
  videoChatRequestResolver,
  updateVideoChatRequestResolver,
  blockResolver,
  unBlockResolver,
  flagVideoResolver,
  deleteVideoResolver,
  lookingForResolver,
  viewVideoResolver,
  googleAppLoginResolver,
  googleAppSignupResolver,
  getExpoTokenResolver,
  appleSignupResolver,
  appleLoginResolver,
  deleteAccountResolver,
  termsAgreementResolver,
  addPhoneResolver,
  sendPhoneNumberResolver,
  callDurationResolver,
  likeResolver,
  unLikeResolver,
  flagPhotoResolver,
  unflagPictureResolver,
  unflagVideoResolver,
  banUserResolver,
  changePlanResolver,
  buyLikesResolver,
  buyMessagesResolver,
  buyVideoMinutesResolver,
  deleteUserResolver,
  deleteSeedersResolver,
  addToQueueResolver,
  matchUserResolver,
  updateMatchStatusResolver,
  removeFromQueueResolver,
  sendTwoFactorResolver,
  resetPasswordResolver,
  earnRewardResolver,
  directUploadResolver,
  directVideoUploadResolver,
} = require("./mutations");

const typeDefs = [rootDefs];

const resolvers = {
  Subscription: {
    roomCreatedOrUpdated: roomCreatedOrUpdatedSubscription,
    createComment: createCommentSubscription,
    createVideo: createVideoSubscription,
    videoChatRequest: videoChatRequestSubscription,
    changePlan: changePlanSubscription,
    buyLikes: buyLikesSubscription,
    buyMessages: buyMessagesSubscription,
    buyVideoMinutes: buyMinutesSubscription,
    flagUser: flagUserSubscription,
    userMatched: userMatchedSubscription,
  },
  Query: {
    fetchMe: fetchMeResolver,
    getRooms: getRoomsResolver,
    getComments: getCommentsResolver,
    findUser: findUserResolver,
    getUsersMap: getUsersMapResolver,
    getAllUsers: getAllUsersResolver,
    getVideos: getVideosResolver,
    getLikedUsers: getLikedUsersResolver,
    getUsersWhoLikedMe: getUsersWhoLikedMeResolver,
    getMatchedUsers: getMatchedUsersResolver,
    getFlaggedPictures: getFlaggedPicturesResolver,
    getFlaggedVideos: getFlaggedVideosResolver,
    getRealUsers: getRealUsersResolver,
  },
  Mutation: {
    createRoom: createRoomResolver,
    changeRoom: changeRoomResolver,
    googleSignup: googleSignupResolver,
    googleLogin: googleLoginResolver,
    signup: signupResolver,
    login: loginResolver,
    logout: logoutResolver,
    createComment: createCommentResolver,
    createProfile: createProfileResolver,
    updateLocation: updateLocationResolver,
    addPhoto: addPhotoResolver,
    flagPhoto: flagPhotoResolver,
    sendVideo: sendVideoResolver,
    deletePhoto: deletePhotoResolver,
    videoChatRequest: videoChatRequestResolver,
    updateVideoChatRequest: updateVideoChatRequestResolver,
    block: blockResolver,
    unBlock: unBlockResolver,
    flagVideo: flagVideoResolver,
    deleteVideo: deleteVideoResolver,
    lookingFor: lookingForResolver,
    viewVideo: viewVideoResolver,
    googleAppLogin: googleAppLoginResolver,
    googleAppSignup: googleAppSignupResolver,
    getExpoToken: getExpoTokenResolver,
    appleSignup: appleSignupResolver,
    appleLogin: appleLoginResolver,
    deleteAccount: deleteAccountResolver,
    termsAgreement: termsAgreementResolver,
    addPhone: addPhoneResolver,
    sendPhoneNumber: sendPhoneNumberResolver,
    callDuration: callDurationResolver,
    like: likeResolver,
    unLike: unLikeResolver,
    unflagPicture: unflagPictureResolver,
    unflagVideo: unflagVideoResolver,
    banUser: banUserResolver,
    changePlan: changePlanResolver,
    buyLikes: buyLikesResolver,
    buyMessages: buyMessagesResolver,
    buyVideoMinutes: buyVideoMinutesResolver,
    deleteUser: deleteUserResolver,
    deleteSeeders: deleteSeedersResolver,
    addToQueue: addToQueueResolver,
    matchUser: matchUserResolver,
    updateMatchStatus: updateMatchStatusResolver,
    removeFromQueue: removeFromQueueResolver,
    sendTwoFactor: sendTwoFactorResolver,
    resetPassword: resetPasswordResolver,
    earnReward: earnRewardResolver,
    directUpload: directUploadResolver,
    directVideoUpload: directVideoUploadResolver,
  },
};

module.exports = { typeDefs, resolvers };
